# Generated by Django 3.2 on 2021-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created on date')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'General Inquiry',
                'verbose_name_plural': 'General Inquiries',
            },
        ),
        migrations.CreateModel(
            name='JobContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created on date')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Job Inquiry',
                'verbose_name_plural': 'Job Inquiries',
            },
        ),
        migrations.CreateModel(
            name='JoinContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created on date')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Join Gym Inquiry',
                'verbose_name_plural': 'Join Inquiries',
            },
        ),
    ]
